-- Extend functional classification tree with full vyhláška coverage.
-- Source: vyhláška č. 412/2021 Sb., příloha č. 3, fetched from
--   https://www.zakonyprolidi.cz/cs/2021-412 (znění od 1. 1. 2026)
--
-- Migration 0002 seeded only paragrafy explicitly listed in
-- docs/budget-categorization.md (an illustrative selection, ~150 paragrafy).
-- This migration extends the tree to the full vyhláška coverage so that:
--   * UI categories industryAndEconomy and environmentAndAgriculture get
--     non-empty paragraph mappings
--   * "drobné" oddíly (36, 38, 39, 64) have paragraphs available for the
--     service layer to address case-by-case
--   * One data bug from 0002 is fixed (paragraf 4141 was placed under
--     pododdíl 413, vyhláška puts it under 414).
--
-- Idempotent strategy: refresh of category_paragraph_map uses
-- ON CONFLICT (category_id, paragraph_id) DO NOTHING — safe on re-run.

-- 1. Fix bug from 0002: paragraf 4141 was wrongly placed under pododdíl 413, belongs under 414
UPDATE functional_paragraphs SET subdivision_id = (SELECT id FROM functional_subdivisions WHERE code = '414') WHERE code = '4141';

-- 2. Add pododdíly missing in 0002
INSERT INTO functional_subdivisions (division_id, code, slug, name_cs) VALUES
  ((SELECT id FROM functional_divisions WHERE code = '10'), '109', 'subdivision-109', 'Ostatní činnost a nespecifikované výdaje'),
  ((SELECT id FROM functional_divisions WHERE code = '21'), '216', 'subdivision-216', 'Správa v odvětví energetiky, průmyslu, stavebnictví, obchodu a služeb'),
  ((SELECT id FROM functional_divisions WHERE code = '21'), '218', 'subdivision-218', 'Výzkum a vývoj v průmyslu, stavebnictví, obchodu a službách'),
  ((SELECT id FROM functional_divisions WHERE code = '21'), '219', 'subdivision-219', 'Ostatní činnost a nespecifikované výdaje'),
  ((SELECT id FROM functional_divisions WHERE code = '22'), '223', 'subdivision-223', 'Vnitrozemská a námořní plavba'),
  ((SELECT id FROM functional_divisions WHERE code = '22'), '227', 'subdivision-227', 'Doprava ostatních drah'),
  ((SELECT id FROM functional_divisions WHERE code = '22'), '228', 'subdivision-228', 'Výzkum v dopravě'),
  ((SELECT id FROM functional_divisions WHERE code = '22'), '229', 'subdivision-229', 'Ostatní činnost a nespecifikované výdaje v dopravě'),
  ((SELECT id FROM functional_divisions WHERE code = '23'), '234', 'subdivision-234', 'Voda v zemědělské krajině'),
  ((SELECT id FROM functional_divisions WHERE code = '23'), '236', 'subdivision-236', 'Správa ve vodním hospodářství'),
  ((SELECT id FROM functional_divisions WHERE code = '23'), '238', 'subdivision-238', 'Vodohospodářský výzkum a vývoj'),
  ((SELECT id FROM functional_divisions WHERE code = '23'), '239', 'subdivision-239', 'Ostatní činnost a nespecifikované výdaje'),
  ((SELECT id FROM functional_divisions WHERE code = '24'), '241', 'subdivision-241', 'Činnosti spojů'),
  ((SELECT id FROM functional_divisions WHERE code = '24'), '246', 'subdivision-246', 'Správa ve spojích'),
  ((SELECT id FROM functional_divisions WHERE code = '24'), '248', 'subdivision-248', 'Výzkum a vývoj ve spojích'),
  ((SELECT id FROM functional_divisions WHERE code = '24'), '249', 'subdivision-249', 'Ostatní činnost a nespecifikované výdaje ve spojích'),
  ((SELECT id FROM functional_divisions WHERE code = '25'), '252', 'subdivision-252', 'Všeobecné pracovní záležitosti'),
  ((SELECT id FROM functional_divisions WHERE code = '25'), '253', 'subdivision-253', 'Všeobecné finanční záležitosti'),
  ((SELECT id FROM functional_divisions WHERE code = '25'), '254', 'subdivision-254', 'Všeobecné hospodářské služby'),
  ((SELECT id FROM functional_divisions WHERE code = '25'), '256', 'subdivision-256', 'Všeobecná hospodářská správa'),
  ((SELECT id FROM functional_divisions WHERE code = '25'), '258', 'subdivision-258', 'Výzkum a vývoj v oblasti všeobecných hospodářských záležitostí'),
  ((SELECT id FROM functional_divisions WHERE code = '25'), '259', 'subdivision-259', 'Ostatní činnosti a nespecifikované výdaje'),
  ((SELECT id FROM functional_divisions WHERE code = '25'), '328', 'subdivision-328', 'Výzkum školství a vzdělávání'),
  ((SELECT id FROM functional_divisions WHERE code = '33'), '336', 'subdivision-336', 'Správa v oblasti kultury, církví a sdělovacích prostředků'),
  ((SELECT id FROM functional_divisions WHERE code = '33'), '338', 'subdivision-338', 'Výzkum a vývoj v oblasti kultury, církví a sdělovacích prostředků'),
  ((SELECT id FROM functional_divisions WHERE code = '33'), '339', 'subdivision-339', 'Ostatní činnosti v záležitostech kultury, církví a sdělovacích prostředků'),
  ((SELECT id FROM functional_divisions WHERE code = '34'), '346', 'subdivision-346', 'Správa v oblasti sportu'),
  ((SELECT id FROM functional_divisions WHERE code = '34'), '348', 'subdivision-348', 'Výzkum v oblasti sportu, zájmové činnosti a rekreace'),
  ((SELECT id FROM functional_divisions WHERE code = '35'), '358', 'subdivision-358', 'Výzkum a vývoj ve zdravotnictví'),
  ((SELECT id FROM functional_divisions WHERE code = '35'), '359', 'subdivision-359', 'Ostatní činnost ve zdravotnictví'),
  ((SELECT id FROM functional_divisions WHERE code = '36'), '366', 'subdivision-366', 'Správa v oblasti bydlení, komunálních služeb a územního rozvoje'),
  ((SELECT id FROM functional_divisions WHERE code = '36'), '368', 'subdivision-368', 'Výzkum a vývoj v oblasti bydlení, komunálních služeb a územního rozvoje'),
  ((SELECT id FROM functional_divisions WHERE code = '36'), '369', 'subdivision-369', 'Ostatní činnost v oblasti bydlení, komunálních služeb a územního rozvoje'),
  ((SELECT id FROM functional_divisions WHERE code = '37'), '375', 'subdivision-375', 'Omezování hluku a vibrací'),
  ((SELECT id FROM functional_divisions WHERE code = '37'), '376', 'subdivision-376', 'Správa v ochraně životního prostředí'),
  ((SELECT id FROM functional_divisions WHERE code = '37'), '377', 'subdivision-377', 'Ochrana proti záření'),
  ((SELECT id FROM functional_divisions WHERE code = '37'), '378', 'subdivision-378', 'Výzkum životního prostředí'),
  ((SELECT id FROM functional_divisions WHERE code = '37'), '379', 'subdivision-379', 'Ostatní činnosti v životním prostředí'),
  ((SELECT id FROM functional_divisions WHERE code = '38'), '380', 'subdivision-380', 'Ostatní výzkum a vývoj'),
  ((SELECT id FROM functional_divisions WHERE code = '39'), '390', 'subdivision-390', 'Ostatní činnosti související se službami pro fyzické osoby'),
  ((SELECT id FROM functional_divisions WHERE code = '41'), '415', 'subdivision-415', 'Zvláštní sociální dávky příslušníků ozbrojených sil a bezpečnostních sborů při skončení služebního poměru'),
  ((SELECT id FROM functional_divisions WHERE code = '42'), '423', 'subdivision-423', 'Ochrana zaměstnanců při platební neschopnosti zaměstnavatelů'),
  ((SELECT id FROM functional_divisions WHERE code = '42'), '424', 'subdivision-424', 'Zaměstnávání zdravotně postižených občanů'),
  ((SELECT id FROM functional_divisions WHERE code = '42'), '425', 'subdivision-425', 'Příspěvky na sociální důsledky restrukturalizace'),
  ((SELECT id FROM functional_divisions WHERE code = '42'), '428', 'subdivision-428', 'Výzkum a vývoj v politice zaměstnanosti'),
  ((SELECT id FROM functional_divisions WHERE code = '43'), '433', 'subdivision-433', 'Sociální péče a pomoc manželství a rodinám'),
  ((SELECT id FROM functional_divisions WHERE code = '43'), '434', 'subdivision-434', 'Sociální rehabilitace a ostatní sociální péče a pomoc'),
  ((SELECT id FROM functional_divisions WHERE code = '43'), '436', 'subdivision-436', 'Správa v sociálním zabezpečení a politice zaměstnanosti'),
  ((SELECT id FROM functional_divisions WHERE code = '43'), '438', 'subdivision-438', 'Výzkum v sociálním zabezpečení a politice zaměstnanosti'),
  ((SELECT id FROM functional_divisions WHERE code = '43'), '439', 'subdivision-439', 'Ostatní činnost a nespecifikované výdaje'),
  ((SELECT id FROM functional_divisions WHERE code = '51'), '516', 'subdivision-516', 'Státní správa ve vojenské obraně'),
  ((SELECT id FROM functional_divisions WHERE code = '51'), '518', 'subdivision-518', 'Výzkum a vývoj v oblasti obrany'),
  ((SELECT id FROM functional_divisions WHERE code = '51'), '519', 'subdivision-519', 'Ostatní záležitosti obrany'),
  ((SELECT id FROM functional_divisions WHERE code = '52'), '526', 'subdivision-526', 'Státní správa v oblasti hospodářských opatření'),
  ((SELECT id FROM functional_divisions WHERE code = '52'), '528', 'subdivision-528', 'Výzkum a vývoj v oblasti civilní připravenosti na krizové stavy'),
  ((SELECT id FROM functional_divisions WHERE code = '52'), '529', 'subdivision-529', 'Ostatní záležitosti civilní připravenosti pro krizové stavy'),
  ((SELECT id FROM functional_divisions WHERE code = '53'), '538', 'subdivision-538', 'Výzkum týkající se bezpečnosti a veřejného pořádku'),
  ((SELECT id FROM functional_divisions WHERE code = '53'), '539', 'subdivision-539', 'Ostatní záležitosti bezpečnosti a veřejného pořádku'),
  ((SELECT id FROM functional_divisions WHERE code = '54'), '546', 'subdivision-546', 'Správa v oblasti právní ochrany'),
  ((SELECT id FROM functional_divisions WHERE code = '54'), '548', 'subdivision-548', 'Výzkum v oblasti právní ochrany'),
  ((SELECT id FROM functional_divisions WHERE code = '54'), '549', 'subdivision-549', 'Ostatní záležitosti právní ochrany'),
  ((SELECT id FROM functional_divisions WHERE code = '55'), '556', 'subdivision-556', 'Státní správa v požární ochraně a integrovaném záchranném systému'),
  ((SELECT id FROM functional_divisions WHERE code = '55'), '558', 'subdivision-558', 'Výzkum a vývoj v požární ochraně a integrovaném záchranném systému'),
  ((SELECT id FROM functional_divisions WHERE code = '55'), '559', 'subdivision-559', 'Ostatní záležitosti požární ochrany a integrovaného záchranného systému'),
  ((SELECT id FROM functional_divisions WHERE code = '61'), '618', 'subdivision-618', 'Výzkum ve státní správě a samosprávě'),
  ((SELECT id FROM functional_divisions WHERE code = '63'), '639', 'subdivision-639', 'Ostatní finanční operace');

-- 3. Add paragrafy missing in 0002
INSERT INTO functional_paragraphs (subdivision_id, code, slug, name_cs) VALUES
  ((SELECT id FROM functional_subdivisions WHERE code = '101'), '1011', 'paragraph-1011', 'Udržování výrobního potenciálu zemědělství, zemědělský půdní fond a mimoprodukční funkce zemědělství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '101'), '1012', 'paragraph-1012', 'Podnikání a restrukturalizace v zemědělství a potravinářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '101'), '1013', 'paragraph-1013', 'Genetický potenciál hospodářských zvířat, osiv a sádí'),
  ((SELECT id FROM functional_subdivisions WHERE code = '101'), '1014', 'paragraph-1014', 'Ozdravování hospodářských zvířat, polních a speciálních plodin a zvláštní veterinární péče'),
  ((SELECT id FROM functional_subdivisions WHERE code = '101'), '1019', 'paragraph-1019', 'Ostatní zemědělská a potravinářská činnost a rozvoj'),
  ((SELECT id FROM functional_subdivisions WHERE code = '102'), '1021', 'paragraph-1021', 'Organizace trhu s produkty rostlinné výroby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '102'), '1022', 'paragraph-1022', 'Organizace trhu s výrobky vzniklými zpracováním produktů rostlinné výroby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '102'), '1023', 'paragraph-1023', 'Organizace trhu s produkty živočišné výroby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '102'), '1024', 'paragraph-1024', 'Organizace trhu s výrobky vzniklými zpracováním produktů živočišné výroby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '102'), '1029', 'paragraph-1029', 'Ostatní záležitosti regulace zemědělské produkce, organizace zemědělského trhu a poskytování podpor'),
  ((SELECT id FROM functional_subdivisions WHERE code = '103'), '1031', 'paragraph-1031', 'Pěstební činnost'),
  ((SELECT id FROM functional_subdivisions WHERE code = '103'), '1032', 'paragraph-1032', 'Podpora ostatních produkčních činností'),
  ((SELECT id FROM functional_subdivisions WHERE code = '103'), '1036', 'paragraph-1036', 'Správa v lesním hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '103'), '1037', 'paragraph-1037', 'Celospolečenské funkce lesů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '103'), '1039', 'paragraph-1039', 'Ostatní záležitosti lesního hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '106'), '1061', 'paragraph-1061', 'Činnost ústředního orgánu státní správy v zemědělství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '106'), '1062', 'paragraph-1062', 'Činnost ostatních orgánů státní správy v zemědělství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '106'), '1063', 'paragraph-1063', 'Správa zemědělského majetku'),
  ((SELECT id FROM functional_subdivisions WHERE code = '106'), '1069', 'paragraph-1069', 'Ostatní správa v zemědělství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '107'), '1070', 'paragraph-1070', 'Rybářství a myslivost'),
  ((SELECT id FROM functional_subdivisions WHERE code = '108'), '1081', 'paragraph-1081', 'Zemědělský výzkum a vývoj'),
  ((SELECT id FROM functional_subdivisions WHERE code = '108'), '1082', 'paragraph-1082', 'Lesnický výzkum'),
  ((SELECT id FROM functional_subdivisions WHERE code = '109'), '1091', 'paragraph-1091', 'Mezinárodní spolupráce v zemědělství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '109'), '1092', 'paragraph-1092', 'Mezinárodní spolupráce v lesním hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '109'), '1098', 'paragraph-1098', 'Ostatní výdaje na zemědělství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '109'), '1099', 'paragraph-1099', 'Ostatní výdaje na lesní hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '211'), '2111', 'paragraph-2111', 'Uhelné hornictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '211'), '2112', 'paragraph-2112', 'Těžba nerostných surovin kromě paliv'),
  ((SELECT id FROM functional_subdivisions WHERE code = '211'), '2113', 'paragraph-2113', 'Zpracování ropy a zemního plynu'),
  ((SELECT id FROM functional_subdivisions WHERE code = '211'), '2114', 'paragraph-2114', 'Jaderné elektrárny'),
  ((SELECT id FROM functional_subdivisions WHERE code = '211'), '2115', 'paragraph-2115', 'Úspora energie a obnovitelné zdroje'),
  ((SELECT id FROM functional_subdivisions WHERE code = '211'), '2116', 'paragraph-2116', 'Jaderné palivo a ochrana před ionizujícím zářením'),
  ((SELECT id FROM functional_subdivisions WHERE code = '211'), '2117', 'paragraph-2117', 'Elektrická energie'),
  ((SELECT id FROM functional_subdivisions WHERE code = '211'), '2118', 'paragraph-2118', 'Energie jiná než elektrická'),
  ((SELECT id FROM functional_subdivisions WHERE code = '211'), '2119', 'paragraph-2119', 'Ostatní záležitosti těžebního průmyslu a energetiky'),
  ((SELECT id FROM functional_subdivisions WHERE code = '212'), '2121', 'paragraph-2121', 'Stavebnictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '212'), '2122', 'paragraph-2122', 'Sběr a zpracování druhotných surovin'),
  ((SELECT id FROM functional_subdivisions WHERE code = '212'), '2123', 'paragraph-2123', 'Podpora rozvoje průmyslových zón'),
  ((SELECT id FROM functional_subdivisions WHERE code = '212'), '2124', 'paragraph-2124', 'Opatření ke zvýšení konkurenceschopnosti průmyslových odvětví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '212'), '2125', 'paragraph-2125', 'Podpora podnikání a inovací'),
  ((SELECT id FROM functional_subdivisions WHERE code = '212'), '2129', 'paragraph-2129', 'Ostatní odvětvová a oborová opatření'),
  ((SELECT id FROM functional_subdivisions WHERE code = '213'), '2131', 'paragraph-2131', 'Přímá podpora exportu'),
  ((SELECT id FROM functional_subdivisions WHERE code = '213'), '2139', 'paragraph-2139', 'Ostatní záležitosti zahraničního obchodu'),
  ((SELECT id FROM functional_subdivisions WHERE code = '214'), '2141', 'paragraph-2141', 'Vnitřní obchod'),
  ((SELECT id FROM functional_subdivisions WHERE code = '214'), '2142', 'paragraph-2142', 'Ubytování a stravování'),
  ((SELECT id FROM functional_subdivisions WHERE code = '214'), '2143', 'paragraph-2143', 'Cestovní ruch'),
  ((SELECT id FROM functional_subdivisions WHERE code = '214'), '2144', 'paragraph-2144', 'Ostatní služby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '216'), '2161', 'paragraph-2161', 'Činnost ústředního orgánu státní správy v odvětví energetiky, průmyslu, stavebnictví, obchodu a služeb'),
  ((SELECT id FROM functional_subdivisions WHERE code = '216'), '2162', 'paragraph-2162', 'Činnost ostatních orgánů státní správy v průmyslu, stavebnictví, obchodu a službách'),
  ((SELECT id FROM functional_subdivisions WHERE code = '216'), '2169', 'paragraph-2169', 'Ostatní správa v průmyslu, stavebnictví, obchodu a službách'),
  ((SELECT id FROM functional_subdivisions WHERE code = '218'), '2181', 'paragraph-2181', 'Výzkum a vývoj v palivech a energetice'),
  ((SELECT id FROM functional_subdivisions WHERE code = '218'), '2182', 'paragraph-2182', 'Výzkum a vývoj v průmyslu kromě paliv a energetiky'),
  ((SELECT id FROM functional_subdivisions WHERE code = '218'), '2183', 'paragraph-2183', 'Výzkum a vývoj ve službách'),
  ((SELECT id FROM functional_subdivisions WHERE code = '218'), '2184', 'paragraph-2184', 'Výzkum a vývoj v obchodu a cestovním ruchu'),
  ((SELECT id FROM functional_subdivisions WHERE code = '218'), '2185', 'paragraph-2185', 'Výzkum a vývoj ve stavebnictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '219'), '2191', 'paragraph-2191', 'Mezinárodní spolupráce v průmyslu, stavebnictví, obchodu a službách'),
  ((SELECT id FROM functional_subdivisions WHERE code = '219'), '2199', 'paragraph-2199', 'Záležitosti průmyslu, stavebnictví, obchodu a služeb jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '222'), '2222', 'paragraph-2222', 'Kontrola technické způsobilosti vozidel'),
  ((SELECT id FROM functional_subdivisions WHERE code = '222'), '2229', 'paragraph-2229', 'Ostatní záležitosti v silniční dopravě'),
  ((SELECT id FROM functional_subdivisions WHERE code = '223'), '2231', 'paragraph-2231', 'Vodní cesty'),
  ((SELECT id FROM functional_subdivisions WHERE code = '223'), '2232', 'paragraph-2232', 'Provoz vnitrozemské plavby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '223'), '2233', 'paragraph-2233', 'Záležitosti námořní dopravy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '223'), '2239', 'paragraph-2239', 'Ostatní záležitosti vnitrozemské plavby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '224'), '2243', 'paragraph-2243', 'Drážní vozidla'),
  ((SELECT id FROM functional_subdivisions WHERE code = '224'), '2249', 'paragraph-2249', 'Ostatní záležitosti železniční dopravy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '225'), '2253', 'paragraph-2253', 'Provoz civilní letecké dopravy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '225'), '2259', 'paragraph-2259', 'Ostatní záležitosti civilní letecké dopravy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '226'), '2261', 'paragraph-2261', 'Činnost ústředních orgánů státní správy v dopravě'),
  ((SELECT id FROM functional_subdivisions WHERE code = '226'), '2262', 'paragraph-2262', 'Činnost ostatních orgánů státní správy v dopravě'),
  ((SELECT id FROM functional_subdivisions WHERE code = '227'), '2271', 'paragraph-2271', 'Ostatní dráhy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '227'), '2272', 'paragraph-2272', 'Provoz ostatních drah'),
  ((SELECT id FROM functional_subdivisions WHERE code = '227'), '2279', 'paragraph-2279', 'Záležitosti ostatních drah jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '228'), '2280', 'paragraph-2280', 'Výzkum a vývoj v dopravě'),
  ((SELECT id FROM functional_subdivisions WHERE code = '229'), '2291', 'paragraph-2291', 'Mezinárodní spolupráce v dopravě'),
  ((SELECT id FROM functional_subdivisions WHERE code = '229'), '2292', 'paragraph-2292', 'Dopravní obslužnost veřejnými službami - linková'),
  ((SELECT id FROM functional_subdivisions WHERE code = '229'), '2293', 'paragraph-2293', 'Dopravní obslužnost mimo veřejnou službu'),
  ((SELECT id FROM functional_subdivisions WHERE code = '229'), '2294', 'paragraph-2294', 'Dopravní obslužnost veřejnými službami - drážní'),
  ((SELECT id FROM functional_subdivisions WHERE code = '229'), '2295', 'paragraph-2295', 'Dopravní obslužnost veřejnými službami - smíšená'),
  ((SELECT id FROM functional_subdivisions WHERE code = '229'), '2299', 'paragraph-2299', 'Ostatní záležitosti v dopravě'),
  ((SELECT id FROM functional_subdivisions WHERE code = '231'), '2310', 'paragraph-2310', 'Pitná voda'),
  ((SELECT id FROM functional_subdivisions WHERE code = '232'), '2321', 'paragraph-2321', 'Odvádění a čistění odpadních vod a nakládání s kaly'),
  ((SELECT id FROM functional_subdivisions WHERE code = '232'), '2322', 'paragraph-2322', 'Prevence znečisťování vody'),
  ((SELECT id FROM functional_subdivisions WHERE code = '232'), '2329', 'paragraph-2329', 'Odvádění a čištění odpadních vod jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '233'), '2331', 'paragraph-2331', 'Úpravy vodohospodářsky významných a vodárenských toků'),
  ((SELECT id FROM functional_subdivisions WHERE code = '233'), '2332', 'paragraph-2332', 'Vodní díla na vodohospodářsky významných a vodárenských tocích'),
  ((SELECT id FROM functional_subdivisions WHERE code = '233'), '2333', 'paragraph-2333', 'Úpravy drobných vodních toků'),
  ((SELECT id FROM functional_subdivisions WHERE code = '233'), '2334', 'paragraph-2334', 'Revitalizace říčních systémů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '233'), '2339', 'paragraph-2339', 'Záležitosti vodních toků a vodohospodářských děl jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '234'), '2341', 'paragraph-2341', 'Vodní díla v zemědělské krajině'),
  ((SELECT id FROM functional_subdivisions WHERE code = '234'), '2342', 'paragraph-2342', 'Protierozní ochrana'),
  ((SELECT id FROM functional_subdivisions WHERE code = '234'), '2349', 'paragraph-2349', 'Ostatní záležitosti vody v zemědělské krajině'),
  ((SELECT id FROM functional_subdivisions WHERE code = '236'), '2361', 'paragraph-2361', 'Činnost ústředních orgánů státní správy ve vodním hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '236'), '2362', 'paragraph-2362', 'Činnost ostatních orgánů státní správy ve vodním hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '236'), '2369', 'paragraph-2369', 'Ostatní správa ve vodním hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '238'), '2380', 'paragraph-2380', 'Vodohospodářský výzkum a vývoj'),
  ((SELECT id FROM functional_subdivisions WHERE code = '239'), '2391', 'paragraph-2391', 'Mezinárodní spolupráce v oblasti vodního hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '239'), '2399', 'paragraph-2399', 'Ostatní záležitosti vodního hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '241'), '2411', 'paragraph-2411', 'Záležitosti pošt'),
  ((SELECT id FROM functional_subdivisions WHERE code = '241'), '2412', 'paragraph-2412', 'Záležitosti telekomunikací'),
  ((SELECT id FROM functional_subdivisions WHERE code = '241'), '2413', 'paragraph-2413', 'Záležitosti radiokomunikací'),
  ((SELECT id FROM functional_subdivisions WHERE code = '241'), '2419', 'paragraph-2419', 'Ostatní záležitosti spojů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '246'), '2461', 'paragraph-2461', 'Činnost ústředních orgánů státní správy ve spojích'),
  ((SELECT id FROM functional_subdivisions WHERE code = '246'), '2462', 'paragraph-2462', 'Činnost ostatních orgánů státní správy ve spojích'),
  ((SELECT id FROM functional_subdivisions WHERE code = '246'), '2469', 'paragraph-2469', 'Ostatní správa ve spojích'),
  ((SELECT id FROM functional_subdivisions WHERE code = '248'), '2480', 'paragraph-2480', 'Výzkum a vývoj ve spojích'),
  ((SELECT id FROM functional_subdivisions WHERE code = '249'), '2491', 'paragraph-2491', 'Mezinárodní spolupráce ve spojích'),
  ((SELECT id FROM functional_subdivisions WHERE code = '249'), '2499', 'paragraph-2499', 'Ostatní záležitosti spojů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '251'), '2510', 'paragraph-2510', 'Podpora podnikání'),
  ((SELECT id FROM functional_subdivisions WHERE code = '252'), '2521', 'paragraph-2521', 'Bezpečnost práce'),
  ((SELECT id FROM functional_subdivisions WHERE code = '252'), '2529', 'paragraph-2529', 'Všeobecné pracovní záležitosti jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '253'), '2531', 'paragraph-2531', 'Česká národní banka a měna'),
  ((SELECT id FROM functional_subdivisions WHERE code = '253'), '2532', 'paragraph-2532', 'Úřad Národní rozpočtové rady'),
  ((SELECT id FROM functional_subdivisions WHERE code = '253'), '2539', 'paragraph-2539', 'Všeobecné finanční záležitosti jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '254'), '2541', 'paragraph-2541', 'Geologie'),
  ((SELECT id FROM functional_subdivisions WHERE code = '254'), '2542', 'paragraph-2542', 'Meteorologie'),
  ((SELECT id FROM functional_subdivisions WHERE code = '254'), '2549', 'paragraph-2549', 'Všeobecné hospodářské služby jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '256'), '2561', 'paragraph-2561', 'Činnost ústředních orgánů státní správy v oblasti hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '256'), '2562', 'paragraph-2562', 'Činnost ostatních orgánů a organizací v oblasti normalizace, standardizace a metrologie'),
  ((SELECT id FROM functional_subdivisions WHERE code = '256'), '2563', 'paragraph-2563', 'Činnost ostatních orgánů státní správy v zeměměřictví a katastru'),
  ((SELECT id FROM functional_subdivisions WHERE code = '256'), '2564', 'paragraph-2564', 'Správa národního majetku'),
  ((SELECT id FROM functional_subdivisions WHERE code = '256'), '2565', 'paragraph-2565', 'Činnost ostatních orgánů státní správy v oblasti bezpečnosti práce'),
  ((SELECT id FROM functional_subdivisions WHERE code = '256'), '2569', 'paragraph-2569', 'Všeobecná hospodářská správa jinde nezařazená'),
  ((SELECT id FROM functional_subdivisions WHERE code = '258'), '2580', 'paragraph-2580', 'Výzkum a vývoj v oblasti všeobecných hospodářských záležitostí'),
  ((SELECT id FROM functional_subdivisions WHERE code = '259'), '2590', 'paragraph-2590', 'Mezinárodní spolupráce ve všeobecných hospodářských záležitostech'),
  ((SELECT id FROM functional_subdivisions WHERE code = '311'), '3115', 'paragraph-3115', 'Ostatní záležitosti předškolního vzdělávání'),
  ((SELECT id FROM functional_subdivisions WHERE code = '311'), '3119', 'paragraph-3119', 'Ostatní záležitosti základního vzdělávání'),
  ((SELECT id FROM functional_subdivisions WHERE code = '312'), '3124', 'paragraph-3124', 'Střední školy a konzervatoře pro žáky se speciálními vzdělávacími potřebami'),
  ((SELECT id FROM functional_subdivisions WHERE code = '312'), '3125', 'paragraph-3125', 'Střediska praktického vyučování a školní hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '312'), '3127', 'paragraph-3127', 'Střední školy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '312'), '3128', 'paragraph-3128', 'Sportovní školy - gymnázia'),
  ((SELECT id FROM functional_subdivisions WHERE code = '312'), '3129', 'paragraph-3129', 'Ostatní zařízení středního vzdělávání'),
  ((SELECT id FROM functional_subdivisions WHERE code = '313'), '3132', 'paragraph-3132', 'Diagnostické ústavy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '313'), '3139', 'paragraph-3139', 'Ostatní školská zařízení pro výkon ústavní a ochranné výchovy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '314'), '3144', 'paragraph-3144', 'Školy v přírodě'),
  ((SELECT id FROM functional_subdivisions WHERE code = '314'), '3145', 'paragraph-3145', 'Internáty'),
  ((SELECT id FROM functional_subdivisions WHERE code = '314'), '3146', 'paragraph-3146', 'Zařízení výchovného poradenství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '314'), '3147', 'paragraph-3147', 'Domovy mládeže'),
  ((SELECT id FROM functional_subdivisions WHERE code = '314'), '3148', 'paragraph-3148', 'Střediska výchovné péče'),
  ((SELECT id FROM functional_subdivisions WHERE code = '314'), '3149', 'paragraph-3149', 'Ostatní zařízení související s výchovou a vzděláváním mládeže'),
  ((SELECT id FROM functional_subdivisions WHERE code = '322'), '3229', 'paragraph-3229', 'Ostatní zařízení související s vysokoškolským vzděláváním'),
  ((SELECT id FROM functional_subdivisions WHERE code = '323'), '3232', 'paragraph-3232', 'Jazykové školy s právem státní jazykové zkoušky'),
  ((SELECT id FROM functional_subdivisions WHERE code = '323'), '3233', 'paragraph-3233', 'Střediska volného času'),
  ((SELECT id FROM functional_subdivisions WHERE code = '323'), '3239', 'paragraph-3239', 'Záležitosti zájmového vzdělávání jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '326'), '3261', 'paragraph-3261', 'Činnost ústředního orgánu státní správy ve vzdělávání'),
  ((SELECT id FROM functional_subdivisions WHERE code = '326'), '3262', 'paragraph-3262', 'Činnost ostatních orgánů státní správy ve vzdělávání'),
  ((SELECT id FROM functional_subdivisions WHERE code = '326'), '3269', 'paragraph-3269', 'Ostatní správa ve vzdělávání jinde nezařazená'),
  ((SELECT id FROM functional_subdivisions WHERE code = '328'), '3280', 'paragraph-3280', 'Výzkum školství a vzdělávání'),
  ((SELECT id FROM functional_subdivisions WHERE code = '329'), '3291', 'paragraph-3291', 'Mezinárodní spolupráce ve vzdělávání'),
  ((SELECT id FROM functional_subdivisions WHERE code = '329'), '3292', 'paragraph-3292', 'Vzdělávání národnostních menšin a multikulturní výchova'),
  ((SELECT id FROM functional_subdivisions WHERE code = '329'), '3293', 'paragraph-3293', 'Vzdělávací akce k integraci Romů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '329'), '3294', 'paragraph-3294', 'Zařízení pro další vzdělávání pedagogických pracovníků'),
  ((SELECT id FROM functional_subdivisions WHERE code = '331'), '3316', 'paragraph-3316', 'Vydavatelská činnost'),
  ((SELECT id FROM functional_subdivisions WHERE code = '331'), '3317', 'paragraph-3317', 'Výstavní činnosti v kultuře'),
  ((SELECT id FROM functional_subdivisions WHERE code = '332'), '3321', 'paragraph-3321', 'Činnosti památkových ústavů, hradů a zámků'),
  ((SELECT id FROM functional_subdivisions WHERE code = '332'), '3324', 'paragraph-3324', 'Výkup předmětů kulturní hodnoty'),
  ((SELECT id FROM functional_subdivisions WHERE code = '332'), '3326', 'paragraph-3326', 'Pořízení, zachování a obnova hodnot místního kulturního, národního a historického povědomí'),
  ((SELECT id FROM functional_subdivisions WHERE code = '332'), '3329', 'paragraph-3329', 'Ostatní záležitosti ochrany památek a péče o kulturní dědictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '334'), '3349', 'paragraph-3349', 'Ostatní záležitosti sdělovacích prostředků'),
  ((SELECT id FROM functional_subdivisions WHERE code = '336'), '3361', 'paragraph-3361', 'Činnost ústředního orgánu státní správy v oblasti kultury a církví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '336'), '3362', 'paragraph-3362', 'Činnost ústředního orgánu státní správy v oblasti sdělovacích prostředků'),
  ((SELECT id FROM functional_subdivisions WHERE code = '336'), '3369', 'paragraph-3369', 'Ostatní správa v oblasti kultury, církví a sdělovacích prostředků'),
  ((SELECT id FROM functional_subdivisions WHERE code = '338'), '3380', 'paragraph-3380', 'Výzkum a vývoj v oblasti kultury, církví a sdělovacích prostředků'),
  ((SELECT id FROM functional_subdivisions WHERE code = '339'), '3391', 'paragraph-3391', 'Mezinárodní spolupráce v kultuře, církvích a sdělovacích prostředcích'),
  ((SELECT id FROM functional_subdivisions WHERE code = '339'), '3392', 'paragraph-3392', 'Zájmová činnost v kultuře'),
  ((SELECT id FROM functional_subdivisions WHERE code = '339'), '3399', 'paragraph-3399', 'Ostatní záležitosti kultury, církví a sdělovacích prostředků'),
  ((SELECT id FROM functional_subdivisions WHERE code = '346'), '3461', 'paragraph-3461', 'Činnost ústředního orgánu státní správy v oblasti sportu'),
  ((SELECT id FROM functional_subdivisions WHERE code = '348'), '3480', 'paragraph-3480', 'Výzkum v oblasti sportu, zájmové činnosti a rekreace'),
  ((SELECT id FROM functional_subdivisions WHERE code = '352'), '3529', 'paragraph-3529', 'Ostatní ústavní péče'),
  ((SELECT id FROM functional_subdivisions WHERE code = '353'), '3539', 'paragraph-3539', 'Ostatní zdravotnická zařízení a služby pro zdravotnictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '354'), '3542', 'paragraph-3542', 'Prevence HIV/AIDS'),
  ((SELECT id FROM functional_subdivisions WHERE code = '354'), '3549', 'paragraph-3549', 'Ostatní speciální zdravotnická péče'),
  ((SELECT id FROM functional_subdivisions WHERE code = '356'), '3561', 'paragraph-3561', 'Činnost ústředního orgánu státní správy ve zdravotnictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '356'), '3562', 'paragraph-3562', 'Činnost ostatních orgánů státní správy ve zdravotnictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '356'), '3569', 'paragraph-3569', 'Ostatní správa ve zdravotnictví jinde nezařazená'),
  ((SELECT id FROM functional_subdivisions WHERE code = '358'), '3581', 'paragraph-3581', 'Organizace výzkumu a střediska vědeckých informací'),
  ((SELECT id FROM functional_subdivisions WHERE code = '358'), '3589', 'paragraph-3589', 'Ostatní výzkum a vývoj ve zdravotnictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '359'), '3591', 'paragraph-3591', 'Mezinárodní spolupráce ve zdravotnictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '359'), '3592', 'paragraph-3592', 'Další vzdělávání pracovníků ve zdravotnictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '359'), '3599', 'paragraph-3599', 'Ostatní činnost ve zdravotnictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '361'), '3611', 'paragraph-3611', 'Podpora individuální bytové výstavby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '361'), '3612', 'paragraph-3612', 'Bytové hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '361'), '3613', 'paragraph-3613', 'Nebytové hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '361'), '3614', 'paragraph-3614', 'Bytové služby pro vlastní zaměstnance'),
  ((SELECT id FROM functional_subdivisions WHERE code = '361'), '3615', 'paragraph-3615', 'Podpora stavebního spoření a hypotečních úvěrů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '361'), '3619', 'paragraph-3619', 'Ostatní rozvoj bydlení a bytového hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '363'), '3631', 'paragraph-3631', 'Veřejné osvětlení'),
  ((SELECT id FROM functional_subdivisions WHERE code = '363'), '3632', 'paragraph-3632', 'Pohřebnictví'),
  ((SELECT id FROM functional_subdivisions WHERE code = '363'), '3633', 'paragraph-3633', 'Výstavba a údržba místních inženýrských sítí'),
  ((SELECT id FROM functional_subdivisions WHERE code = '363'), '3634', 'paragraph-3634', 'Lokální zásobování teplem'),
  ((SELECT id FROM functional_subdivisions WHERE code = '363'), '3635', 'paragraph-3635', 'Územní plánování'),
  ((SELECT id FROM functional_subdivisions WHERE code = '363'), '3636', 'paragraph-3636', 'Územní rozvoj'),
  ((SELECT id FROM functional_subdivisions WHERE code = '363'), '3639', 'paragraph-3639', 'Komunální služby a územní rozvoj jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '366'), '3661', 'paragraph-3661', 'Činnost ústředního orgánu státní správy v oblasti bydlení, komunálních služeb a územního rozvoje'),
  ((SELECT id FROM functional_subdivisions WHERE code = '366'), '3662', 'paragraph-3662', 'Činnost ostatních orgánů státní správy v oblasti bydlení, komunálních služeb a územního rozvoje'),
  ((SELECT id FROM functional_subdivisions WHERE code = '366'), '3669', 'paragraph-3669', 'Ostatní správa v oblasti bydlení, komunálních služeb a územního rozvoje jinde nezařazená'),
  ((SELECT id FROM functional_subdivisions WHERE code = '368'), '3680', 'paragraph-3680', 'Výzkum a vývoj v oblasti bydlení, komunálních služeb a územního rozvoje'),
  ((SELECT id FROM functional_subdivisions WHERE code = '369'), '3691', 'paragraph-3691', 'Mezinárodní spolupráce v oblasti bydlení, komunálních služeb a územního rozvoje'),
  ((SELECT id FROM functional_subdivisions WHERE code = '369'), '3699', 'paragraph-3699', 'Ostatní záležitosti bydlení, komunálních služeb a územního rozvoje'),
  ((SELECT id FROM functional_subdivisions WHERE code = '371'), '3713', 'paragraph-3713', 'Změny technologií vytápění'),
  ((SELECT id FROM functional_subdivisions WHERE code = '371'), '3715', 'paragraph-3715', 'Změny výrobních technologií za účelem výrazného odstranění emisí'),
  ((SELECT id FROM functional_subdivisions WHERE code = '371'), '3719', 'paragraph-3719', 'Ostatní činnosti k ochraně ovzduší'),
  ((SELECT id FROM functional_subdivisions WHERE code = '372'), '3721', 'paragraph-3721', 'Sběr a svoz nebezpečných odpadů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '372'), '3723', 'paragraph-3723', 'Sběr a svoz ostatních odpadů jiných než nebezpečných a komunálních'),
  ((SELECT id FROM functional_subdivisions WHERE code = '372'), '3724', 'paragraph-3724', 'Využívání a zneškodňování nebezpečných odpadů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '372'), '3726', 'paragraph-3726', 'Využívání a zneškodňování ostatních odpadů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '372'), '3727', 'paragraph-3727', 'Prevence vzniku odpadů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '372'), '3728', 'paragraph-3728', 'Monitoring nakládání s odpady'),
  ((SELECT id FROM functional_subdivisions WHERE code = '372'), '3729', 'paragraph-3729', 'Ostatní nakládání s odpady'),
  ((SELECT id FROM functional_subdivisions WHERE code = '373'), '3731', 'paragraph-3731', 'Ochrana půdy a podzemní vody proti znečišťujícím infiltracím'),
  ((SELECT id FROM functional_subdivisions WHERE code = '373'), '3732', 'paragraph-3732', 'Dekontaminace půd a čištění spodní vody'),
  ((SELECT id FROM functional_subdivisions WHERE code = '373'), '3733', 'paragraph-3733', 'Monitoring půdy a podzemní vody'),
  ((SELECT id FROM functional_subdivisions WHERE code = '373'), '3734', 'paragraph-3734', 'Předcházení a sanace zasolení půd'),
  ((SELECT id FROM functional_subdivisions WHERE code = '373'), '3739', 'paragraph-3739', 'Ostatní ochrana půdy a spodní vody'),
  ((SELECT id FROM functional_subdivisions WHERE code = '374'), '3743', 'paragraph-3743', 'Rekultivace půdy v důsledku těžební a důlní činnosti, po skládkách odpadů apod.'),
  ((SELECT id FROM functional_subdivisions WHERE code = '374'), '3744', 'paragraph-3744', 'Protierozní, protilavinová a protipožární ochrana'),
  ((SELECT id FROM functional_subdivisions WHERE code = '374'), '3745', 'paragraph-3745', 'Péče o vzhled obcí a veřejnou zeleň'),
  ((SELECT id FROM functional_subdivisions WHERE code = '374'), '3749', 'paragraph-3749', 'Ostatní činnosti k ochraně přírody a krajiny'),
  ((SELECT id FROM functional_subdivisions WHERE code = '375'), '3751', 'paragraph-3751', 'Konstrukce a uplatnění protihlukových zařízení'),
  ((SELECT id FROM functional_subdivisions WHERE code = '375'), '3753', 'paragraph-3753', 'Monitoring ke zjišťování úrovně hluku a vibrací'),
  ((SELECT id FROM functional_subdivisions WHERE code = '375'), '3759', 'paragraph-3759', 'Ostatní činnosti k omezení hluku a vibrací'),
  ((SELECT id FROM functional_subdivisions WHERE code = '376'), '3761', 'paragraph-3761', 'Činnost ústředního orgánu státní správy v ochraně životního prostředí'),
  ((SELECT id FROM functional_subdivisions WHERE code = '376'), '3762', 'paragraph-3762', 'Činnost ostatních orgánů státní správy v ochraně životního prostředí'),
  ((SELECT id FROM functional_subdivisions WHERE code = '376'), '3769', 'paragraph-3769', 'Ostatní správa v ochraně životního prostředí'),
  ((SELECT id FROM functional_subdivisions WHERE code = '377'), '3771', 'paragraph-3771', 'Protiradonová opatření'),
  ((SELECT id FROM functional_subdivisions WHERE code = '377'), '3772', 'paragraph-3772', 'Přeprava a nakládání s radioaktivním odpadem'),
  ((SELECT id FROM functional_subdivisions WHERE code = '377'), '3773', 'paragraph-3773', 'Monitoring k zajišťování úrovně radioaktivního záření'),
  ((SELECT id FROM functional_subdivisions WHERE code = '377'), '3779', 'paragraph-3779', 'Ostatní činnosti k ochraně proti záření'),
  ((SELECT id FROM functional_subdivisions WHERE code = '378'), '3780', 'paragraph-3780', 'Výzkum životního prostředí'),
  ((SELECT id FROM functional_subdivisions WHERE code = '379'), '3791', 'paragraph-3791', 'Mezinárodní spolupráce v životním prostředí'),
  ((SELECT id FROM functional_subdivisions WHERE code = '379'), '3792', 'paragraph-3792', 'Ekologická výchova a osvěta'),
  ((SELECT id FROM functional_subdivisions WHERE code = '379'), '3793', 'paragraph-3793', 'Ekologie v dopravě'),
  ((SELECT id FROM functional_subdivisions WHERE code = '379'), '3799', 'paragraph-3799', 'Ostatní ekologické záležitosti'),
  ((SELECT id FROM functional_subdivisions WHERE code = '380'), '3801', 'paragraph-3801', 'Akademie věd České republiky'),
  ((SELECT id FROM functional_subdivisions WHERE code = '380'), '3802', 'paragraph-3802', 'Grantová agentura České republiky'),
  ((SELECT id FROM functional_subdivisions WHERE code = '380'), '3803', 'paragraph-3803', 'Technologická agentura České republiky'),
  ((SELECT id FROM functional_subdivisions WHERE code = '380'), '3809', 'paragraph-3809', 'Ostatní výzkum a vývoj odvětvově nespecifikovaný'),
  ((SELECT id FROM functional_subdivisions WHERE code = '390'), '3900', 'paragraph-3900', 'Ostatní činnosti související se službami pro fyzické osoby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '411'), '4119', 'paragraph-4119', 'Ostatní dávky důchodového pojištění'),
  ((SELECT id FROM functional_subdivisions WHERE code = '412'), '4123', 'paragraph-4123', 'Vyrovnávací příspěvek v těhotenství a mateřství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '412'), '4129', 'paragraph-4129', 'Dávky nemocenského pojištění jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '413'), '4132', 'paragraph-4132', 'Sociální příplatek'),
  ((SELECT id FROM functional_subdivisions WHERE code = '414'), '4142', 'paragraph-4142', 'Příspěvek na školní pomůcky'),
  ((SELECT id FROM functional_subdivisions WHERE code = '414'), '4149', 'paragraph-4149', 'Dávky státní sociální podpory jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '415'), '4151', 'paragraph-4151', 'Odchodné'),
  ((SELECT id FROM functional_subdivisions WHERE code = '415'), '4152', 'paragraph-4152', 'Výsluhový příspěvek'),
  ((SELECT id FROM functional_subdivisions WHERE code = '415'), '4153', 'paragraph-4153', 'Úmrtné a příspěvek na pohřeb příslušníka'),
  ((SELECT id FROM functional_subdivisions WHERE code = '415'), '4154', 'paragraph-4154', 'Odbytné'),
  ((SELECT id FROM functional_subdivisions WHERE code = '415'), '4159', 'paragraph-4159', 'Ostatní sociální dávky příslušníků ozbrojených sil a bezpečnostních sborů při skončení služebního poměru'),
  ((SELECT id FROM functional_subdivisions WHERE code = '417'), '4177', 'paragraph-4177', 'Mimořádná okamžitá pomoc osobám ohroženým sociálním vyloučením'),
  ((SELECT id FROM functional_subdivisions WHERE code = '417'), '4179', 'paragraph-4179', 'Ostatní dávky sociální pomoci'),
  ((SELECT id FROM functional_subdivisions WHERE code = '418'), '4182', 'paragraph-4182', 'Příspěvek na zvláštní pomůcky'),
  ((SELECT id FROM functional_subdivisions WHERE code = '418'), '4183', 'paragraph-4183', 'Příspěvek na úpravu a provoz bezbariérového bytu'),
  ((SELECT id FROM functional_subdivisions WHERE code = '418'), '4184', 'paragraph-4184', 'Příspěvky na zakoupení, opravu a zvláštní úpravu motorového vozidla'),
  ((SELECT id FROM functional_subdivisions WHERE code = '418'), '4185', 'paragraph-4185', 'Příspěvek na provoz motorového vozidla'),
  ((SELECT id FROM functional_subdivisions WHERE code = '418'), '4186', 'paragraph-4186', 'Příspěvek na individuální dopravu'),
  ((SELECT id FROM functional_subdivisions WHERE code = '418'), '4189', 'paragraph-4189', 'Ostatní dávky zdravotně postiženým občanům'),
  ((SELECT id FROM functional_subdivisions WHERE code = '419'), '4191', 'paragraph-4191', 'Státní příspěvky na důchodové připojištění'),
  ((SELECT id FROM functional_subdivisions WHERE code = '419'), '4192', 'paragraph-4192', 'Úrokové příspěvky mladým manželstvím'),
  ((SELECT id FROM functional_subdivisions WHERE code = '419'), '4193', 'paragraph-4193', 'Dávky válečným veteránům a perzekvovaným osobám'),
  ((SELECT id FROM functional_subdivisions WHERE code = '419'), '4194', 'paragraph-4194', 'Zvýšení důchodů pro bezmocnost'),
  ((SELECT id FROM functional_subdivisions WHERE code = '419'), '4196', 'paragraph-4196', 'Náhradní výživné pro nezaopatřené dítě'),
  ((SELECT id FROM functional_subdivisions WHERE code = '419'), '4197', 'paragraph-4197', 'Dávka státní sociální pomoci'),
  ((SELECT id FROM functional_subdivisions WHERE code = '419'), '4199', 'paragraph-4199', 'Ostatní dávky povahy sociálního zabezpečení jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '422'), '4225', 'paragraph-4225', 'Podpora zaměstnanosti zdravotně postižených občanů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '422'), '4226', 'paragraph-4226', 'Ostatní podpora zaměstnanosti'),
  ((SELECT id FROM functional_subdivisions WHERE code = '422'), '4229', 'paragraph-4229', 'Aktivní politika zaměstnanosti jinde nezařazená'),
  ((SELECT id FROM functional_subdivisions WHERE code = '423'), '4230', 'paragraph-4230', 'Ochrana zaměstnanců při platební neschopnosti zaměstnavatelů'),
  ((SELECT id FROM functional_subdivisions WHERE code = '424'), '4240', 'paragraph-4240', 'Příspěvek na podporu zaměstnávání osob se zdravotním postižením na chráněném trhu práce'),
  ((SELECT id FROM functional_subdivisions WHERE code = '425'), '4250', 'paragraph-4250', 'Příspěvky na sociální důsledky restrukturalizace'),
  ((SELECT id FROM functional_subdivisions WHERE code = '428'), '4280', 'paragraph-4280', 'Výzkum a vývoj v politice zaměstnanosti'),
  ((SELECT id FROM functional_subdivisions WHERE code = '431'), '4311', 'paragraph-4311', 'Základní sociální poradenství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '431'), '4312', 'paragraph-4312', 'Odborné sociální poradenství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '431'), '4319', 'paragraph-4319', 'Ostatní výdaje související se sociálním poradenstvím'),
  ((SELECT id FROM functional_subdivisions WHERE code = '432'), '4329', 'paragraph-4329', 'Ostatní sociální péče a pomoc dětem a mládeži'),
  ((SELECT id FROM functional_subdivisions WHERE code = '433'), '4334', 'paragraph-4334', 'Pečovatelská služba pro rodinu a děti'),
  ((SELECT id FROM functional_subdivisions WHERE code = '433'), '4339', 'paragraph-4339', 'Ostatní sociální péče a pomoc rodině a manželství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '434'), '4341', 'paragraph-4341', 'Sociální pomoc osobám v hmotné nouzi a občanům sociálně nepřizpůsobivým'),
  ((SELECT id FROM functional_subdivisions WHERE code = '434'), '4342', 'paragraph-4342', 'Sociální péče a pomoc přistěhovalcům a vybraným etnikům'),
  ((SELECT id FROM functional_subdivisions WHERE code = '434'), '4343', 'paragraph-4343', 'Sociální pomoc osobám v souvislosti s živelní pohromou nebo požárem'),
  ((SELECT id FROM functional_subdivisions WHERE code = '434'), '4344', 'paragraph-4344', 'Sociální rehabilitace'),
  ((SELECT id FROM functional_subdivisions WHERE code = '434'), '4345', 'paragraph-4345', 'Centra sociálně rehabilitačních služeb'),
  ((SELECT id FROM functional_subdivisions WHERE code = '434'), '4349', 'paragraph-4349', 'Ostatní sociální péče a pomoc ostatním skupinám fyzických osob'),
  ((SELECT id FROM functional_subdivisions WHERE code = '435'), '4352', 'paragraph-4352', 'Tísňová péče'),
  ((SELECT id FROM functional_subdivisions WHERE code = '435'), '4353', 'paragraph-4353', 'Průvodcovské a předčitatelské služby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '435'), '4355', 'paragraph-4355', 'Týdenní stacionáře'),
  ((SELECT id FROM functional_subdivisions WHERE code = '435'), '4358', 'paragraph-4358', 'Sociální služby poskytované ve zdravotnických zařízeních ústavní péče'),
  ((SELECT id FROM functional_subdivisions WHERE code = '435'), '4359', 'paragraph-4359', 'Ostatní služby a činnosti v oblasti sociální péče'),
  ((SELECT id FROM functional_subdivisions WHERE code = '436'), '4361', 'paragraph-4361', 'Činnost ústředního orgánu státní správy v sociálním zabezpečení, politice zaměstnanosti a rodinné politice'),
  ((SELECT id FROM functional_subdivisions WHERE code = '436'), '4362', 'paragraph-4362', 'Činnost ostatních orgánů státní správy v sociálním zabezpečení'),
  ((SELECT id FROM functional_subdivisions WHERE code = '436'), '4363', 'paragraph-4363', 'Ostatní orgány státní správy v oblasti politiky zaměstnanosti'),
  ((SELECT id FROM functional_subdivisions WHERE code = '436'), '4369', 'paragraph-4369', 'Ostatní správa v sociálním zabezpečení a politice zaměstnanosti'),
  ((SELECT id FROM functional_subdivisions WHERE code = '437'), '4371', 'paragraph-4371', 'Raná péče a sociálně aktivizační služby pro rodiny s dětmi'),
  ((SELECT id FROM functional_subdivisions WHERE code = '437'), '4372', 'paragraph-4372', 'Krizová pomoc'),
  ((SELECT id FROM functional_subdivisions WHERE code = '437'), '4373', 'paragraph-4373', 'Domy na půl cesty'),
  ((SELECT id FROM functional_subdivisions WHERE code = '437'), '4375', 'paragraph-4375', 'Nízkoprahová zařízení pro děti a mládež'),
  ((SELECT id FROM functional_subdivisions WHERE code = '437'), '4376', 'paragraph-4376', 'Služby následné péče, terapeutické komunity a kontaktní centra'),
  ((SELECT id FROM functional_subdivisions WHERE code = '437'), '4377', 'paragraph-4377', 'Sociálně terapeutické dílny'),
  ((SELECT id FROM functional_subdivisions WHERE code = '437'), '4378', 'paragraph-4378', 'Terénní programy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '437'), '4379', 'paragraph-4379', 'Ostatní služby a činnosti v oblasti sociální prevence'),
  ((SELECT id FROM functional_subdivisions WHERE code = '438'), '4380', 'paragraph-4380', 'Výzkum v sociálním zabezpečení a politice zaměstnanosti'),
  ((SELECT id FROM functional_subdivisions WHERE code = '439'), '4391', 'paragraph-4391', 'Mezinárodní spolupráce v sociálním zabezpečení a podpoře zaměstnanosti'),
  ((SELECT id FROM functional_subdivisions WHERE code = '439'), '4392', 'paragraph-4392', 'Inspekce poskytování sociálních služeb'),
  ((SELECT id FROM functional_subdivisions WHERE code = '439'), '4399', 'paragraph-4399', 'Ostatní záležitosti sociálních věcí a politiky zaměstnanosti'),
  ((SELECT id FROM functional_subdivisions WHERE code = '516'), '5161', 'paragraph-5161', 'Činnost ústředního orgánu státní správy ve vojenské obraně'),
  ((SELECT id FROM functional_subdivisions WHERE code = '516'), '5162', 'paragraph-5162', 'Činnost ostatních orgánů státní správy ve vojenské obraně'),
  ((SELECT id FROM functional_subdivisions WHERE code = '516'), '5169', 'paragraph-5169', 'Ostatní správa ve vojenské obraně'),
  ((SELECT id FROM functional_subdivisions WHERE code = '517'), '5172', 'paragraph-5172', 'Operační příprava státního území'),
  ((SELECT id FROM functional_subdivisions WHERE code = '517'), '5179', 'paragraph-5179', 'Ostatní činnosti pro zabezpečení potřeb ozbrojených sil'),
  ((SELECT id FROM functional_subdivisions WHERE code = '518'), '5180', 'paragraph-5180', 'Výzkum a vývoj v oblasti obrany'),
  ((SELECT id FROM functional_subdivisions WHERE code = '519'), '5191', 'paragraph-5191', 'Mezinárodní spolupráce v obraně'),
  ((SELECT id FROM functional_subdivisions WHERE code = '519'), '5192', 'paragraph-5192', 'Zahraniční vojenská pomoc'),
  ((SELECT id FROM functional_subdivisions WHERE code = '519'), '5199', 'paragraph-5199', 'Ostatní záležitosti obrany'),
  ((SELECT id FROM functional_subdivisions WHERE code = '521'), '5211', 'paragraph-5211', 'Civilní ochrana - vojenská část'),
  ((SELECT id FROM functional_subdivisions WHERE code = '521'), '5212', 'paragraph-5212', 'Ochrana obyvatelstva'),
  ((SELECT id FROM functional_subdivisions WHERE code = '521'), '5213', 'paragraph-5213', 'Krizová opatření'),
  ((SELECT id FROM functional_subdivisions WHERE code = '521'), '5219', 'paragraph-5219', 'Ostatní záležitosti ochrany fyzických osob'),
  ((SELECT id FROM functional_subdivisions WHERE code = '522'), '5220', 'paragraph-5220', 'Hospodářská opatření pro krizové stavy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '526'), '5261', 'paragraph-5261', 'Státní správa v oblasti hospodářských opatření pro krizové stavy a v oblasti krizového řízení'),
  ((SELECT id FROM functional_subdivisions WHERE code = '526'), '5262', 'paragraph-5262', 'Činnost ostatních orgánů státní správy v oblasti civilního nouzového hospodářství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '526'), '5269', 'paragraph-5269', 'Ostatní správa v oblasti hospodářských opatření pro krizové stavy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '527'), '5271', 'paragraph-5271', 'Činnost orgánů krizového řízení na ústřední úrovni a dalších správních úřadů v oblasti krizového řízení'),
  ((SELECT id FROM functional_subdivisions WHERE code = '527'), '5272', 'paragraph-5272', 'Činnost orgánů krizového řízení na územní úrovni a dalších územních správních úřadů v oblasti krizového řízení'),
  ((SELECT id FROM functional_subdivisions WHERE code = '527'), '5273', 'paragraph-5273', 'Ostatní správa v oblasti krizového řízení'),
  ((SELECT id FROM functional_subdivisions WHERE code = '527'), '5274', 'paragraph-5274', 'Podpora krizového řízení a nouzového plánování'),
  ((SELECT id FROM functional_subdivisions WHERE code = '527'), '5279', 'paragraph-5279', 'Záležitosti krizového řízení jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '528'), '5281', 'paragraph-5281', 'Výzkum a vývoj v oblasti ochrany fyzických osob'),
  ((SELECT id FROM functional_subdivisions WHERE code = '528'), '5289', 'paragraph-5289', 'Výzkum a vývoj v oblasti krizového řízení'),
  ((SELECT id FROM functional_subdivisions WHERE code = '529'), '5291', 'paragraph-5291', 'Mezinárodní spolupráce v oblasti krizového řízení'),
  ((SELECT id FROM functional_subdivisions WHERE code = '529'), '5292', 'paragraph-5292', 'Poskytnutí vzájemné zahraniční pomoci podle mezinárodních smluv'),
  ((SELECT id FROM functional_subdivisions WHERE code = '529'), '5299', 'paragraph-5299', 'Ostatní záležitosti civilní připravenosti na krizové stavy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '531'), '5316', 'paragraph-5316', 'Činnost ústředního orgánu státní správy v oblasti bezpečnosti a veřejného pořádku'),
  ((SELECT id FROM functional_subdivisions WHERE code = '531'), '5319', 'paragraph-5319', 'Ostatní záležitosti bezpečnosti a veřejného pořádku'),
  ((SELECT id FROM functional_subdivisions WHERE code = '538'), '5380', 'paragraph-5380', 'Výzkum týkající se bezpečnosti a veřejného pořádku'),
  ((SELECT id FROM functional_subdivisions WHERE code = '539'), '5391', 'paragraph-5391', 'Mezinárodní spolupráce v oblasti bezpečnosti a veřejného pořádku'),
  ((SELECT id FROM functional_subdivisions WHERE code = '539'), '5399', 'paragraph-5399', 'Ostatní záležitosti bezpečnosti, veřejného pořádku'),
  ((SELECT id FROM functional_subdivisions WHERE code = '542'), '5420', 'paragraph-5420', 'Soudy'),
  ((SELECT id FROM functional_subdivisions WHERE code = '544'), '5442', 'paragraph-5442', 'Ostatní správa ve vězeňství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '544'), '5449', 'paragraph-5449', 'Ostatní záležitosti vězeňství'),
  ((SELECT id FROM functional_subdivisions WHERE code = '546'), '5461', 'paragraph-5461', 'Činnost ústředního orgánu státní správy v oblasti právní ochrany'),
  ((SELECT id FROM functional_subdivisions WHERE code = '546'), '5462', 'paragraph-5462', 'Činnost ostatních orgánů státní správy v oblasti právní ochrany'),
  ((SELECT id FROM functional_subdivisions WHERE code = '546'), '5469', 'paragraph-5469', 'Ostatní správa v oblasti právní ochrany'),
  ((SELECT id FROM functional_subdivisions WHERE code = '547'), '5471', 'paragraph-5471', 'Kancelář finančního arbitra'),
  ((SELECT id FROM functional_subdivisions WHERE code = '548'), '5480', 'paragraph-5480', 'Výzkum v oblasti právní ochrany'),
  ((SELECT id FROM functional_subdivisions WHERE code = '549'), '5491', 'paragraph-5491', 'Mezinárodní spolupráce v oblasti právní ochrany'),
  ((SELECT id FROM functional_subdivisions WHERE code = '549'), '5499', 'paragraph-5499', 'Ostatní záležitosti právní ochrany'),
  ((SELECT id FROM functional_subdivisions WHERE code = '551'), '5519', 'paragraph-5519', 'Ostatní záležitosti požární ochrany'),
  ((SELECT id FROM functional_subdivisions WHERE code = '552'), '5522', 'paragraph-5522', 'Ostatní činnosti v integrovaném záchranném systému'),
  ((SELECT id FROM functional_subdivisions WHERE code = '552'), '5529', 'paragraph-5529', 'Ostatní složky a činnosti integrovaného záchranného systému'),
  ((SELECT id FROM functional_subdivisions WHERE code = '556'), '5561', 'paragraph-5561', 'Činnost ústředního orgánu státní správy v požární ochraně'),
  ((SELECT id FROM functional_subdivisions WHERE code = '556'), '5562', 'paragraph-5562', 'Činnost ústředních orgánů státní správy v integrovaném záchranném systému'),
  ((SELECT id FROM functional_subdivisions WHERE code = '556'), '5563', 'paragraph-5563', 'Činnost ostatních orgánů státní správy v integrovaném záchranném systému'),
  ((SELECT id FROM functional_subdivisions WHERE code = '558'), '5580', 'paragraph-5580', 'Výzkum a vývoj v požární ochraně a integrovaném záchranném systému'),
  ((SELECT id FROM functional_subdivisions WHERE code = '559'), '5591', 'paragraph-5591', 'Mezinárodní spolupráce v oblasti požární ochrany a integrovaném záchranném systému'),
  ((SELECT id FROM functional_subdivisions WHERE code = '559'), '5592', 'paragraph-5592', 'Poskytnutí vzájemné zahraniční pomoci podle mezinárodních smluv'),
  ((SELECT id FROM functional_subdivisions WHERE code = '559'), '5599', 'paragraph-5599', 'Ostatní záležitosti požární ochrany a integrovaného záchranného systému'),
  ((SELECT id FROM functional_subdivisions WHERE code = '611'), '6116', 'paragraph-6116', 'Celostátní referendum'),
  ((SELECT id FROM functional_subdivisions WHERE code = '611'), '6119', 'paragraph-6119', 'Ostatní zastupitelské orgány a volby'),
  ((SELECT id FROM functional_subdivisions WHERE code = '614'), '6148', 'paragraph-6148', 'Plánování a statistika'),
  ((SELECT id FROM functional_subdivisions WHERE code = '614'), '6149', 'paragraph-6149', 'Ostatní všeobecná vnitřní správa jinde nezařazená'),
  ((SELECT id FROM functional_subdivisions WHERE code = '615'), '6153', 'paragraph-6153', 'Ostatní účast v mezinárodních vládních organizacích'),
  ((SELECT id FROM functional_subdivisions WHERE code = '615'), '6159', 'paragraph-6159', 'Zahraniční služba a záležitosti jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '617'), '6173', 'paragraph-6173', 'Místní referendum'),
  ((SELECT id FROM functional_subdivisions WHERE code = '618'), '6180', 'paragraph-6180', 'Výzkum ve státní správě a samosprávě'),
  ((SELECT id FROM functional_subdivisions WHERE code = '621'), '6219', 'paragraph-6219', 'Ostatní veřejné služby jinde nezařazené'),
  ((SELECT id FROM functional_subdivisions WHERE code = '622'), '6221', 'paragraph-6221', 'Humanitární zahraniční pomoc přímá'),
  ((SELECT id FROM functional_subdivisions WHERE code = '622'), '6223', 'paragraph-6223', 'Mezinárodní spolupráce jinde nezařazená'),
  ((SELECT id FROM functional_subdivisions WHERE code = '622'), '6229', 'paragraph-6229', 'Ostatní zahraniční pomoc'),
  ((SELECT id FROM functional_subdivisions WHERE code = '639'), '6391', 'paragraph-6391', 'Soudní a mimosoudní rehabilitace'),
  ((SELECT id FROM functional_subdivisions WHERE code = '639'), '6399', 'paragraph-6399', 'Ostatní finanční operace'),
  ((SELECT id FROM functional_subdivisions WHERE code = '640'), '6401', 'paragraph-6401', 'Transfery všeobecné povahy jiným úrovním vlády'),
  ((SELECT id FROM functional_subdivisions WHERE code = '640'), '6402', 'paragraph-6402', 'Finanční vypořádání'),
  ((SELECT id FROM functional_subdivisions WHERE code = '640'), '6409', 'paragraph-6409', 'Ostatní činnosti jinde nezařazené');

-- 4. Refresh category_paragraph_map for new paragrafy (idempotent via ON CONFLICT)

INSERT INTO category_paragraph_map (category_id, paragraph_id)
SELECT (SELECT id FROM categories WHERE slug = 'socialProtection'), fp.id
FROM functional_paragraphs fp
JOIN functional_subdivisions fs ON fs.id = fp.subdivision_id
WHERE fs.division_id IN (SELECT id FROM functional_divisions WHERE code IN ('41', '42', '43'))
ON CONFLICT (category_id, paragraph_id) DO NOTHING;

INSERT INTO category_paragraph_map (category_id, paragraph_id)
SELECT (SELECT id FROM categories WHERE slug = 'transport'), fp.id
FROM functional_paragraphs fp
JOIN functional_subdivisions fs ON fs.id = fp.subdivision_id
WHERE fs.division_id IN (SELECT id FROM functional_divisions WHERE code IN ('22', '23'))
ON CONFLICT (category_id, paragraph_id) DO NOTHING;

INSERT INTO category_paragraph_map (category_id, paragraph_id)
SELECT (SELECT id FROM categories WHERE slug = 'environmentAndAgriculture'), fp.id
FROM functional_paragraphs fp
JOIN functional_subdivisions fs ON fs.id = fp.subdivision_id
WHERE fs.division_id IN (SELECT id FROM functional_divisions WHERE code IN ('10', '37'))
ON CONFLICT (category_id, paragraph_id) DO NOTHING;

INSERT INTO category_paragraph_map (category_id, paragraph_id)
SELECT (SELECT id FROM categories WHERE slug = 'industryAndEconomy'), fp.id
FROM functional_paragraphs fp
JOIN functional_subdivisions fs ON fs.id = fp.subdivision_id
WHERE fs.division_id IN (SELECT id FROM functional_divisions WHERE code IN ('21', '24', '25'))
ON CONFLICT (category_id, paragraph_id) DO NOTHING;

-- Stats: 66 new pododdíly, 372 new paragrafy
